##########################################################################################
# To create a K8s secret for pulling images from GHCR in this GitHub organization,
# please replace the username, password, email and auth placeholders with actual values.
#
# To generate BASE64_OF_USERNAME:PASSWORD, execute the following from a shell terminal:
#
# echo -n "<your-argocd-machine-username>:<your-argocd-machine-user-GitHub-PAT>" | base64
# 
# Be sure to use a GitHub Argo CD machine user and PAT with permissions to access GHCR 
# i.e. read packages permissions.
# Once you've replaced the username, password, email and auth placeholders with actual
# values, execute the following from a shell terminal:
#
# ./setup-argocd.sh
#
# NOTE: This secret can be set once for the entire GitHub organization and will be
# used by Argo CD to pull container images from GitHub Container Registry (ghcr.io)
# for all environments. You do not need to create separate secrets for each environment
# repository (argocd-dev, argocd-qa, argocd-staging, argocd-prod), but you *do* need to 
# apply the secret to every K8s cluster you will deploy to via Argo CD.
#
##########################################################################################

apiVersion: v1
kind: Namespace
metadata:
  name: ${GITHUB_ORG}
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  namespace: ${GITHUB_ORG}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "${ARGOCD_MACHINE_USER}",
          "password": "${GITHUB_TOKEN}",
          "email": "${ARGOCD_MACHINE_EMAIL}",
          "auth": "${GHCR_AUTH_BASE64}"
        }
      }
    }
    
